### ISSUE TITLE
ap 15, 3-4 

### ISSUE THREAD

**Issue by cusmai** [BibleGet-I-O/endpoint#15]
CEI2008

"ap 15, 3" returns verses 3 and 4. 
"ap 15, 4" returns zero results.

**Comment by JohnRDOrazio** [comment]
confirmed for the version CEI2008. It was an error in the database. It's now fixed, however if you are using the WordPress plugin, it's internal cacheing will still have the old results for 7 days. If this is the case and you need to flush the cache there, you can go to the BibleGet settings area and there is an option to flush the Bible verses cache.
