### ISSUE TITLE
Ap 22,1

### ISSUE THREAD

**Issue by cusmai** [BibleGet-I-O/endpoint#17]
CEI2008

Database error in Ap 22,1 (Italian)

"In questo apparato sono riportate le principali varianti che caratterizzano la Nova Vulgata (NVg) rispetto al testo critico seguito nella presente traduzione. Viene indicato il versetto, o la parte di esso, che differisce per cambiamento del testo (invece), o aggiunta (aggiunge). Le parole sono variate come indicato in nota"

**Comment by JohnRDOrazio** [comment]
grazie per la segnalazione, anche questo ora corretto. Se trovi qualche altro refuso continua a segnalare!
